spring:
  application:
    name: FlightsSpring
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: ${FLIGHTS_SPRING_POSTGRE_URL} # Environment variable
    username: ${FLIGHTS_SPRING_POSTGRE_USERNAME} # Environment variable
    password: ${FLIGHTS_SPRING_POSTGRE_PASSWORD} # Environment variable
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Checks if the database schema matches the models, but does not make any changes

server:
  port: 8080
  servlet:
    encoding:
      force-response: true
      charset: UTF-8

api:
  name: Flights API
  version: 0.0.2
  path: /flights/api/v1

security:
  jwt-secret: ${FLIGHTS_SPRING_JWT_SECRET} # Environment variable
  jwt-expiration-time-ms: 3600000

custom-config: # Some custom configs
  root-user: # Root user realization
    allow-root: false # Allow root account
    username: ${FLIGHTS_SPRING_ROOT_USERNAME} # Environment variable
    password: ${FLIGHTS_SPRING_ROOT_PASSWORD} # Environment variable
  log-mappings: true # Logging endpoint controllers mappings in console during application starting
  log-aspects: # Aspect logging configs
    enabled: true # Enable aspect logging in controllers and services methods
    print-exception-stacktrace: true
    log-services:
      calls: false # Log services methods calls
      exceptions: true # Log exceptions in services methods
    log-controllers:
      calls: false # Log controllers methods calls
      exceptions: false # Log exceptions in controllers methods

spring-doc:
  swagger-ui:
    enabled: true
    display-request-duration: true